name: Semantic Release & Publish
on:
  push:
    branches: [main]
jobs:
  test:
    runs-on: ubuntu-lastest
    steps:
      - uses: actions/checkout@v3
      - run: yarn install --frozen-lockfile
      - run: yarn test
      - name: Release & Publish
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release
